apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: unicorn-rentals
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
